styles:
    inputs:
        - 'bundles/oroshoppinglist/default/scss/variables/matrix-order-widget-config.scss'
        - 'bundles/oroshoppinglist/default/scss/components/my-shopping-list-owner-wrapper.scss'

        - 'bundles/oroshoppinglist/default/scss/styles.scss'
