operations:
    oro_shoppinglist_frontend_edit_action:
        label: oro.shoppinglist.edit.action.label
        datagrid_options:
            aria_label: oro.frontend.shoppinglist.btn.edit.aria_label
        acl_resource: ['oro_shopping_list_frontend_update', $.data]
        groups:
            - shopping_list_actions
        routes:
            - oro_shopping_list_frontend_view_grid
        button_options:
            icon: fa-pencil-square-o
        actions:
            - '@redirect':
                route: oro_shopping_list_frontend_update
                route_parameters: {id: $id}

    oro_shoppinglist_frontend_duplicate_action:
        label: oro.shoppinglist.duplicate.action.label
        extends: oro_shoppinglist_frontend_duplicate
        replace:
            - button_options
            - frontend_options
            - datagrid_options
            - groups
        button_options:
            icon: fa-clone
        frontend_options:
            show_dialog: true
            confirmation:
                title: oro.frontend.shoppinglist.dialog.duplicate_confirmation.label
                message: oro.frontend.shoppinglist.dialog.duplicate_confirmation.message
                ok: oro.frontend.shoppinglist.dialog.duplicate_ok.label
        datagrid_options:
            aria_label: oro.frontend.shoppinglist.btn.duplicate.aria_label
        groups:
            - shopping_list_actions
        routes:
            - oro_shopping_list_frontend_view_grid
            - oro_shopping_list_frontend_update
        preactions:
            - '@call_service_method':
                attribute: $.isOneShoppingList
                service: oro_shopping_list.manager.shopping_list_limit
                method: isOnlyOneEnabled
        preconditions:
            '@and':
                - '@equal': [$.isOneShoppingList, false]
        actions:
            - '@redirect':
                route: 'oro_shopping_list_frontend_view_grid'
                route_parameters:
                    id: $.newShoppingList.id

    oro_shoppinglist_frontend_delete_action:
        label: oro.shoppinglist.delete.action.label
        extends: oro_shoppinglist_delete
        replace:
            - button_options
            - frontend_options
            - datagrid_options
            - groups
        button_options:
            icon: fa-trash
        frontend_options:
            show_dialog: true
            confirmation:
                title: oro.frontend.shoppinglist.dialog.delete_confirmation.label
                message: oro.frontend.shoppinglist.dialog.delete_confirmation.message
                ok: oro.frontend.shoppinglist.dialog.delete_ok.label
        datagrid_options:
            aria_label: oro.frontend.shoppinglist.btn.delete_aria_label
        groups:
            - shopping_list_actions
        routes:
            - oro_shopping_list_frontend_view_grid
            - oro_shopping_list_frontend_update
        actions:
            - '@redirect':
                route: 'oro_shopping_list_frontend_index'

    oro_shoppinglist_frontend_set_as_default_action:
        label: oro.shoppinglist.set_as_default.action.label
        acl_resource: ['EDIT', $.data]
        button_options:
            icon: fa-check
        frontend_options:
            show_dialog: true
            confirmation:
                title: oro.frontend.shoppinglist.dialog.set_as_default_confirmation.label
                message: oro.frontend.shoppinglist.dialog.set_as_default_confirmation.message
                ok: oro.frontend.shoppinglist.dialog.set_as_default_ok.label
        datagrid_options:
            aria_label: oro.frontend.shoppinglist.btn.set_as_default.aria_label
        groups:
            - shopping_list_actions
        routes:
            - oro_shopping_list_frontend_view_grid
            - oro_shopping_list_frontend_update
        preconditions:
            '@equal': [false, $.data.current]
        actions:
            - '@get_active_user': $.currentUser
            - '@call_service_method':
                service: oro_shopping_list.manager.current_shopping_list
                method: setCurrent
                method_parameters: [$.currentUser, $.data]
            - '@flash_message':
                message: oro.frontend.shoppinglist.messages.set_default_success
                type: 'success'

    oro_shoppinglist_frontend_rename_action:
        label: oro.shoppinglist.rename.action.label
        acl_resource: ['EDIT', $.data]
        button_options:
            icon: fa-pencil
        frontend_options:
            template: OroShoppingListBundle:Action:shoppingListActionRename.html.twig
            title: oro.frontend.shoppinglist.view.rename.label
            show_dialog: true
            options:
                dialogClass: shopping-list-rename-dialog-widget shopping-list-rename-wrapper
                okText: oro.frontend.shoppinglist.btn.rename.label
        attributes:
            label:
                type: entity
                property_path: data.label
                options:
                    class: 'Oro\Bundle\ShoppingListBundle\Entity\ShoppingList'
        form_options:
            attribute_fields:
                label:
                    form_type: Symfony\Component\Form\Extension\Core\Type\TextType
                    options:
                        required: true
                        constraints:
                            - NotBlank: ~
        datagrid_options:
            aria_label: oro.frontend.shoppinglist.btn.rename.aria_label
        groups:
            - shopping_list_actions
        routes:
            - oro_shopping_list_frontend_view_grid
            - oro_shopping_list_frontend_update
        preactions:
            - '@get_active_user': $.currentUser
            - '@call_service_method':
                attribute: $.isOneShoppingList
                service: oro_shopping_list.manager.shopping_list_limit
                method: isOnlyOneEnabled
        preconditions:
            '@and':
                - '@not_empty': $.currentUser
                - '@equal': [$.isOneShoppingList, false]
        actions:
            - '@flush_entity': $.data
            - '@flash_message':
                message: oro.frontend.shoppinglist.messages.rename_success
                type: 'success'
