api:
    entity_aliases:
        Oro\Bundle\CMSBundle\Entity\Page:
            alias:        landingpage
            plural_alias: landingpages

    entities:
        Oro\Bundle\CMSBundle\Entity\Page:
            documentation_resource: '@OroCMSBundle/Resources/doc/api_frontend/page.md'
            fields:
                title:
                    data_type: localizedFallbackValue:titles
                content:
                    data_type: string
                    property_path: _
                    depends_on: [content, content_style]
                _content:
                    exclude: true
                    property_path: content
                contentStyle:
                    exclude: true
                    property_path: content_style
                contentProperties:
                    exclude: true
                    property_path: content_properties
                url:
                    data_type: string
                    property_path: _
                urls:
                    data_type: objects
                    property_path: _
                draftUuid:
                    exclude: true
                draftSource:
                    exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
