Oro\Bundle\CatalogBundle\Model\CategoryUnitPrecision:
    properties:
        precision:
            - NotBlank:
                message: 'oro.product.productunit.precision.blank'
            - Range:
                min: 0
                max: 10
            - Oro\Bundle\ValidationBundle\Validator\Constraints\Integer: ~

Oro\Bundle\CatalogBundle\Entity\Category:
    properties:
        titles:
            - Oro\Bundle\LocaleBundle\Validator\Constraints\NotBlankDefaultLocalizedFallbackValue:
                errorMessage: oro.catalog.category.title.blank
            - Valid: ~
        shortDescriptions:
            - Valid: ~
        longDescriptions:
            - Valid: ~
        slugPrototypes:
            - Valid: ~
