services:
    oro_cms.api.resource_type_resolver.landing_page:
        class: Oro\Bundle\FrontendBundle\Api\ResourceTypeResolver
        arguments:
            - 'landing_page'
        tags:
            - { name: oro_frontend.api.resource_type_resolver, routeName: oro_cms_frontend_page_view }

    oro_cms.api.resource_api_url_resolver.landing_page:
        class: Oro\Bundle\FrontendBundle\Api\ResourceRestApiGetActionUrlResolver
        arguments:
            - '@router'
            - '@oro_api.rest.routes_registry'
            - '@oro_api.value_normalizer'
            - Oro\Bundle\CMSBundle\Entity\Page
        tags:
            - { name: oro_frontend.api.resource_api_url_resolver, routeName: oro_cms_frontend_page_view, requestType: rest }

    oro_cms.api.wysiwyg_value_renderer:
        class: Oro\Bundle\CMSBundle\Api\WYSIWYGValueRenderer
        arguments:
            - '@twig'

    oro_cms.api.frontend.localized_fallback_value_extractor:
        class: Oro\Bundle\CMSBundle\Api\LocalizedFallbackValueExtractor
        decorates: oro_frontend.api.localized_fallback_value_extractor
        arguments:
            - '@oro_cms.api.frontend.localized_fallback_value_extractor.inner'
            - '@oro_cms.api.wysiwyg_value_renderer'
            - '@oro_api.form_property_accessor'

    oro_cms.api.compute_landing_page_urls:
        class: Oro\Bundle\RedirectBundle\Api\Processor\ComputeUrlFields
        arguments:
            - '@oro_api.doctrine_helper'
            - '@oro_locale.helper.localization'
            - '@oro_config.manager'
            - '@router'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, collection: true, class: Oro\Bundle\CMSBundle\Entity\Page }

    oro_cms.api.compute_landing_page_content:
        class: Oro\Bundle\CMSBundle\Api\Processor\ComputeRenderedWYSIWYGField
        arguments:
            - '@oro_cms.api.wysiwyg_value_renderer'
            - 'content'
            - '_content'
            - 'contentStyle'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, requestType: frontend, class: Oro\Bundle\CMSBundle\Entity\Page }
